-- Seed data for the `spots` table, sourced from real Creatrip listings
-- (scraped page dumps under place_DB/urltotext/, one file per Creatrip spot id).
--
-- Generated from 50 places across dermatology, hair-salon, and
-- k-beauty categories. A handful of scraped ids were excluded: two dermatology
-- listings were Busan branches (out of scope — this catalog is Seoul-only), and
-- a few files were empty scrapes. Several ids filed under the hair_salon/ folder
-- turned out to be k-beauty listings by the page's own category tag, not hair
-- salons — parent_category below reflects the page's real category, not the
-- scrape folder.
--
-- booking_url embeds Miyeon's Creatrip affiliate tracking params (utm_source
-- and aff_id = AFF-e2873zu), matching src/lib/creatrip.ts#withCreatripAffiliate.
--
-- Coordinates were geocoded via OpenStreetMap Nominatim against the scraped
-- address; where no street address was captured in the scrape, coordinates
-- fall back to the named neighborhood/station centroid (see each row's source
-- JSON in the extraction — not preserved here) rather than being fabricated.
-- price_min/price_max/opening_hours/duration_min are left null where the
-- scrape had no reliable figure — most listing pages didn't expose a real
-- price table or venue hours (only unrelated boilerplate), so these were not
-- guessed.
--
-- Run after supabase/spots_schema.sql has created the table.

insert into spots (id, name, parent_category, subcategory, description, area, address, latitude, longitude, price_min, price_max, duration_min, opening_hours, booking_required, booking_url, languages, downtime, procedure_intensity, needle_required, tourist_friendly, factory_like, upselling_risk, price_transparency, rating, review_count, experience_style)
values
  ('13071', 'S: Re Born Clinic', 'dermatology', 'skin-care', 'Ultherapy-focused lifting clinic near Hongik Univ. Station, with a chief-director consultation track and strong Chinese-language support for first-time visitors.', 'Hongdae', '162 Yanghwa-ro, Mapo-gu, Seoul', 37.5563863, 126.9238407, 81, 247, null, 'Mon-Wed & Fri 10:30-14:00, 15:00-20:30; Thu 13:00-21:00; Sat 10:00-16:00; Sun Closed', true, 'https://creatrip.com/en/spot/13071?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Korean', 'Chinese']::text[], 'few-hours', 'medium', true, true, false, false, true, 4.9, 685, 'medical'),
  ('13214', 'Cheongdam Éclat De', 'dermatology', 'skin-care', 'Chief-doctor-led Cheongdam dermatology clinic known for its UltraClear laser program and full English/Chinese/Japanese consultation support.', 'Gangnam', '420 Dosan-daero, Gangnam-gu, Seoul', 37.5232381, 127.0419014, null, null, null, null, true, 'https://creatrip.com/en/spot/13214?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Korean', 'Chinese', 'Japanese']::text[], 'few-hours', 'medium', false, true, false, false, true, 4.9, 257, 'medical'),
  ('13335', 'Onlif Clinic', 'dermatology', 'skin-care', 'Lifting-specialty skin clinic near Gangnam Station, built around Thermage/Ultherapy-style devices with full English/Chinese/Japanese support.', 'Gangnam', '399 Gangnam-daero, Seocho-gu, Seoul', 37.4982352, 127.0268207, null, null, null, null, true, 'https://creatrip.com/en/spot/13335?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Korean', 'Chinese', 'Japanese']::text[], 'few-hours', 'medium', false, true, false, false, true, 4.9, 1355, 'medical'),
  ('13573', 'Medicube Clinic Gangnam', 'dermatology', 'skin-care', 'Gangnam skincare clinic from the Medicube brand, a few minutes from Sinnonhyeon Station, focused on brightening and acne-care treatments.', 'Gangnam', '463 Gangnam-daero, Seocho-gu, Seoul', 37.4820127, 127.0368243, null, null, null, null, true, 'https://creatrip.com/en/spot/13573?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Korean', 'Chinese', 'Japanese']::text[], 'none', 'low', false, true, false, false, true, 5, 905, 'professional'),
  ('13898', 'Yonseiro Clinic', 'dermatology', 'skin-care', 'Jongno skin clinic near Gyeongbokgung and central Seoul''s sights, offering quick ''petite'' skin procedures at the same price for locals and foreigners.', null, '57 Sambong-ro, Jongno-gu, Seoul', 37.5725898, 126.9804973, null, null, null, null, true, 'https://creatrip.com/en/spot/13898?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Korean', 'Chinese', 'Japanese']::text[], 'none', 'low', false, true, false, false, true, 4.8, 43, 'professional'),
  ('14201', 'MeSO nBOM Clinic', 'dermatology', 'skin-care', 'Hongdae aesthetic clinic in the Kakao Friends Flagship building at Hongik Univ. Station Exit 8, specializing in RF microneedling and medical facials.', 'Hongdae', '162 Yanghwa-ro, Mapo-gu, Seoul', 37.5563863, 126.9238407, null, null, null, null, true, 'https://creatrip.com/en/spot/14201?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Korean']::text[], 'few-hours', 'medium', true, true, false, false, true, 4.9, 1149, 'medical'),
  ('14275', 'Project U Clinic', 'dermatology', 'skin-care', 'Hongdae skin clinic right by Hongik Univ. Station Exit 8, specializing in filler and Rejuran skin-booster treatments.', 'Hongdae', '162 Yanghwa-ro, Mapo-gu, Seoul', 37.5563863, 126.9238407, null, null, null, null, true, 'https://creatrip.com/en/spot/14275?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Korean', 'Chinese', 'Japanese']::text[], 'few-hours', 'medium', true, true, false, false, true, 5, 417, 'medical'),
  ('14592', 'Abijou Clinic Global Myeongdong', 'dermatology', 'skin-care', 'Long-running Myeongdong dermatology clinic, two minutes from Euljiro 1-ga Station, with two decades of foreigner-focused practice.', 'Myeongdong', '78 Namdaemun-ro, Jung-gu, Seoul', 37.5642888, 126.9829236, null, null, null, null, true, 'https://creatrip.com/en/spot/14592?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Korean', 'Chinese', 'Japanese']::text[], 'few-hours', 'medium', false, true, false, false, true, 4.9, 4460, 'medical'),
  ('14593', 'Abijou Clinic Global Gangnam', 'dermatology', 'skin-care', 'Gangnam branch of the 20-year foreigner-friendly Abijou dermatology group, a minute from Gangnam Station Exit 10.', 'Gangnam', '9 Seocho-daero 77-gil, Seocho-gu, Seoul', 37.498583, 127.0262116, null, null, null, null, true, 'https://creatrip.com/en/spot/14593?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Korean', 'Chinese', 'Japanese']::text[], 'few-hours', 'medium', false, true, false, false, true, 4.9, 1668, 'medical'),
  ('15076', 'DIORE CLINIC', 'dermatology', 'skin-care', 'Private aesthetic clinic three minutes from Gangnam Station Exit 11, focused on lifting treatments, with online consultation available.', 'Gangnam', '428 Gangnam-daero, Gangnam-gu, Seoul', 37.5009318, 127.0266693, null, null, null, 'Weekdays 10:30-20:30; Weekends & holidays 10:00-17:00', true, 'https://creatrip.com/en/spot/15076?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Korean', 'Chinese', 'Japanese']::text[], 'few-hours', 'medium', false, true, false, false, true, 4.8, 760, 'medical'),
  ('15112', 'LIJIN Clinic', 'dermatology', 'skin-care', 'Myeongdong dermatology and laser clinic near Myeongdong Station Exit 6, offering Botox, fillers, and acne/pigmentation treatment with English-speaking staff.', 'Myeongdong', '55 Namdaemun-ro, Jung-gu, Seoul', 37.5624772, 126.9809968, null, null, null, 'Weekdays 09:30-20:30; Weekends 09:30-19:30', true, 'https://creatrip.com/en/spot/15112?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Korean', 'Chinese', 'Japanese']::text[], 'few-hours', 'medium', true, true, false, false, true, 4.9, 177, 'medical'),
  ('15196', 'DayBeau Clinic Gangnam', 'dermatology', 'skin-care', 'Standalone-building Gangnam dermatology clinic; Creatrip bookings include 10 free sheet masks.', 'Gangnam', '494 Gangnam-daero, Gangnam-gu, Seoul', 37.4841386, 127.0342658, null, null, null, null, true, 'https://creatrip.com/en/spot/15196?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Korean', 'Chinese', 'Japanese']::text[], 'none', 'low', false, true, false, false, true, 4.9, 1500, 'professional'),
  ('15197', 'DayBeau Clinic Myeongdong The Luxe', 'dermatology', 'skin-care', 'Premium Myeongdong branch of DayBeau Clinic with private solo VIP treatment rooms, near Lotte Department Store.', 'Myeongdong', '90 Namdaemun-ro, Jung-gu, Seoul', 37.561364, 126.9794708, null, null, null, null, true, 'https://creatrip.com/en/spot/15197?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Korean', 'Chinese', 'Japanese']::text[], 'none', 'low', false, true, false, false, true, 4.9, 322, 'professional'),
  ('15274', 'DayBeau Clinic Myeongdong 2nd Branch', 'dermatology', 'skin-care', 'Second Myeongdong location of DayBeau Clinic; Creatrip bookings include 10 free sheet masks.', 'Myeongdong', '84 Namdaemun-ro, Jung-gu, Seoul', 37.5646213, 126.9827355, null, null, null, null, true, 'https://creatrip.com/en/spot/15274?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Korean', 'Chinese', 'Japanese']::text[], 'none', 'low', false, true, false, false, true, 4.9, 152, 'professional'),
  ('15357', 'OTENA CLINIC', 'dermatology', 'skin-care', 'Myeongdong skin clinic on the 17th floor of Semicolon Myeongdong, positioned on affordable pricing and private treatment rooms.', 'Myeongdong', '90 Namdaemun-ro, Jung-gu, Seoul', 37.561364, 126.9794708, null, null, null, null, true, 'https://creatrip.com/en/spot/15357?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Korean']::text[], 'none', 'low', false, true, false, false, true, 4.9, 2935, 'professional'),
  ('15440', 'Doctor Petit Clinic Hongdae', 'dermatology', 'skin-care', 'New Hongdae medical-aesthetics clinic near Hongik Univ. Station Exit 1, part of the Doctor Petit clinic group.', 'Hongdae', '151 Yanghwa-ro, Mapo-gu, Seoul', 37.5562884, 126.9223535, null, null, null, '10:30-20:30', true, 'https://creatrip.com/en/spot/15440?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Korean', 'Chinese', 'Japanese']::text[], 'few-hours', 'medium', false, true, false, false, true, 5, 204, 'medical'),
  ('15631', 'Arumdaun Nara Dermatology Clinic', 'dermatology', 'skin-care', 'Gangnam anti-aging and lifting dermatology clinic a minute from Gangnam Station Exit 1, with dermatologists overseeing consultation through procedure.', 'Gangnam', '390 Gangnam-daero, Gangnam-gu, Seoul', 37.4978321, 127.0286068, null, null, null, null, true, 'https://creatrip.com/en/spot/15631?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Korean', 'Chinese', 'Japanese']::text[], 'few-hours', 'medium', false, true, false, false, true, 4.7, 159, 'medical'),
  ('11093', 'SOONSIKI Hair Hongdae Flagship', 'hair-salon', 'color-perm', 'Creatrip''s most-booked hair salon, popular with Korean models and celebrities, with English-speaking staff, a dedicated head-spa floor, and transparent no-surprise pricing.', 'Hongdae', '29 Wausan-ro 21-gil, Mapo-gu, Seoul', 37.5522122, 126.9223679, null, null, 360, 'Wed-Sun 10:00-19:00 (Closed Mon & Tue)', true, 'https://creatrip.com/en/spot/11093?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Korean']::text[], 'none', 'medium', false, true, false, false, true, 4.9, 7937, 'korean'),
  ('11331', 'JUNO HAIR Myeongdong 2nd', 'hair-salon', 'color-perm', 'Central Myeongdong JUNO Hair branch known for attentive scalp treatments and cuts, with Chinese-speaking staff, a short walk from Myeongdong Station.', 'Myeongdong', '18 Myeongdong 8na-gil, Jung-gu, Seoul', 37.5617707, 126.9848871, null, null, null, '10:00-21:30 daily', true, 'https://creatrip.com/en/spot/11331?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Korean', 'Chinese']::text[], 'none', 'low', false, true, false, false, true, 4.9, 2543, 'korean'),
  ('13165', 'HOSU DOSAN', 'k-beauty', 'beauty-makeup', 'Celebrity-frequented hair, makeup, and K-beauty aesthetic studio near Apgujeong Rodeo Station, combining skin care, styling, and an optional profile photo shoot in one visit.', 'Gangnam', 'Apgujeong-ro, Gangnam-gu, Seoul (near Apgujeong Rodeo Station)', 37.5267971, 127.0445388, 19, 19, null, null, true, 'https://creatrip.com/en/spot/13165?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Korean']::text[], 'none', 'low', false, true, false, false, true, 4.9, 796, 'korean'),
  ('13466', 'JUNO Hair Myeongdong Street Branch', 'hair-salon', 'color-perm', 'Foreigner-friendly Myeongdong salon known for a relaxing multi-step head spa and English/Chinese/Japanese-speaking staff, with private treatment rooms.', 'Myeongdong', '7F, 41 Myeongdong 10-gil, Jung-gu, Seoul', 37.5615874, 126.9860253, 97, 158, 90, null, true, 'https://creatrip.com/en/spot/13466?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Chinese', 'Japanese']::text[], 'none', 'medium', false, true, false, false, true, 5, 13257, 'relaxing'),
  ('13574', 'Soonsoo', 'k-beauty', 'beauty-makeup', 'Cheongdam hair and makeup salon trusted by K-pop idols (BLACKPINK, NCT, IVE) and leading actors for natural, camera-ready styling.', 'Gangnam', 'Cheongdam-dong, Gangnam-gu, Seoul', 37.5257536, 127.0523217, 99, 99, null, null, true, 'https://creatrip.com/en/spot/13574?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Korean']::text[], 'none', 'low', false, true, false, false, true, 4.3, 249, 'korean'),
  ('13767', 'Moclock Gangnam Main Branch', 'hair-salon', 'head-spa', 'Scalp-focused head spa offering personalized hair-loss and scalp-condition analysis, with treatments for dandruff, itchiness, and seborrheic dermatitis alongside relaxation care.', 'Gangnam', 'Gangnam-gu, Seoul', 37.5177, 127.0473, null, null, null, null, true, 'https://creatrip.com/en/spot/13767?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Korean']::text[], 'none', 'low', false, true, false, false, true, 4.9, 179, 'professional'),
  ('13772', 'The Day''s Hair', 'hair-salon', 'color-perm', 'English-friendly Hongdae salon specializing in men''s cuts, perms, and personal-color-coordinated color using L''Oréal Professionnel and Milbon products.', 'Hongdae', 'Hongdae, Mapo-gu, Seoul', 37.55792, 126.926135, null, null, null, null, true, 'https://creatrip.com/en/spot/13772?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Korean']::text[], 'none', 'medium', false, true, false, false, true, 4.9, 1734, 'professional'),
  ('13789', 'HAUT BEAUTE', 'k-beauty', 'beauty-makeup', 'Trendy, sophisticated Korean-style hair and makeup studio in Gangnam with personalized styling and celebrity-trusted service.', 'Gangnam', 'Gangnam-gu, Seoul', 37.5177, 127.0473, null, null, null, null, true, 'https://creatrip.com/en/spot/13789?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Korean']::text[], 'none', 'low', false, true, false, false, true, 4.8, 87, 'korean'),
  ('13808', 'SOONSIKI Hair Hongdae Hanok Branch', 'hair-salon', 'color-perm', 'SOONSIKI''s Hongdae Hanok branch — the brand''s most-booked location for international guests, offering the same transparent-pricing K-beauty hair styling as the flagship.', 'Hongdae', '19 Hongik-ro 5-gil, Mapo-gu, Seoul', 37.5539505, 126.9213718, null, null, null, null, true, 'https://creatrip.com/en/spot/13808?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Korean']::text[], 'none', 'medium', false, true, false, false, true, 5, 1260, 'korean'),
  ('13814', 'Jenny House', 'k-beauty', 'beauty-makeup', 'JennyHouse Beauty Salon in Cheongdam — a full K-beauty studio offering makeup, hair styling, and head spa in one visit.', 'Gangnam', 'Cheongdam-dong, Gangnam-gu, Seoul', 37.5257536, 127.0523217, 82, 82, null, null, true, 'https://creatrip.com/en/spot/13814?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Korean']::text[], 'none', 'low', false, true, false, false, true, 4.5, 283, 'korean'),
  ('13940', 'ONYAD HAIR', 'hair-salon', 'color-perm', 'Seongsu salon specializing in trendy, personalized styling consultations to find the right look for each guest, with a 10% Creatrip booking discount.', 'Seongsu', 'Seongsu-dong, Seongdong-gu, Seoul', 37.5416233, 127.0387072, null, null, null, null, true, 'https://creatrip.com/en/spot/13940?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Korean']::text[], 'none', 'low', false, true, false, false, true, 4.8, 342, 'korean'),
  ('13957', 'GREEN Scalp & Hair Loss Care Center', 'hair-salon', 'head-spa', 'Myeongdong scalp clinic with 25 years of hair-loss and scalp-care practice, offering diagnostic and therapeutic scalp treatments.', 'Myeongdong', 'Myeongdong, Jung-gu, Seoul', 37.5608977, 126.9863762, 73, 73, null, null, true, 'https://creatrip.com/en/spot/13957?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Korean']::text[], 'none', 'medium', false, true, false, false, true, 5, 45, 'professional'),
  ('14426', '#CCONTE Seogyo Branch', 'hair-salon', 'color-perm', 'Hongdae (Seogyo) color specialist known for bold bleaching and balayage using L''Oréal, Wella, and Milbon products, with English-speaking consultants for international guests.', 'Hongdae', 'Hongdae, Mapo-gu, Seoul', 37.55792, 126.926135, null, null, null, null, true, 'https://creatrip.com/en/spot/14426?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Korean']::text[], 'none', 'medium', false, true, false, false, true, 4.9, 2308, 'korean'),
  ('14720', 'ECO JARDIN Myeongdong Branch', 'hair-salon', 'color-perm', 'Premium scalp and hair care using Shiseido, L''Oréal, and Milbon products, with an 18-step head spa option in central Myeongdong.', 'Myeongdong', 'Myeongdong, Jung-gu, Seoul', 37.5608977, 126.9863762, null, null, null, null, true, 'https://creatrip.com/en/spot/14720?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Korean']::text[], 'none', 'low', false, true, false, false, true, 4.9, 513, 'relaxing'),
  ('14835', 'SOONSIKI Hair Seongsu', 'hair-salon', 'color-perm', 'Seongsu location of Creatrip''s most-booked hair salon brand, delivering trendsetting K-beauty cuts, color, and styling favored by Korean models and celebrities.', 'Seongsu', 'Seongsu-dong, Seongdong-gu, Seoul', 37.5416233, 127.0387072, null, null, null, null, true, 'https://creatrip.com/en/spot/14835?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Korean']::text[], 'none', 'medium', false, true, false, false, true, 4.9, 236, 'korean'),
  ('14846', 'AKNACK Seongsu', 'hair-salon', 'color-perm', 'Detail-focused Seongsu hair salon known among locals for precision cuts tailored to face and head shape rather than a fixed style catalog.', 'Seongsu', 'Seongsu-dong, Seongdong-gu, Seoul', 37.5416233, 127.0387072, null, null, null, null, true, 'https://creatrip.com/en/spot/14846?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Korean']::text[], 'none', 'low', false, true, false, false, true, 5, 151, 'korean'),
  ('14884', 'ECO JARDIN Gyeongbokgung Branch', 'k-beauty', 'beauty-makeup', 'Full-image studio near Gyeongbokgung Palace offering personal color analysis, hair, makeup, perm, and color plus customized scalp-care programs in a single appointment.', null, 'Gyeongbokgung area, Jongno-gu, Seoul', 37.579754, 126.9766818, null, null, null, null, true, 'https://creatrip.com/en/spot/14884?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Korean']::text[], 'none', 'low', false, true, false, false, true, 4.9, 3063, 'korean'),
  ('15429', '#CCONTE Hongdae Yeonam Branch', 'hair-salon', 'color-perm', 'Hongdae/Yeonnam-dong color specialist for bold, fashion-forward bleach and color styles, with personalized consultations based on face shape and skin tone.', 'Hongdae', 'Yeonnam-dong, Mapo-gu, Seoul', 37.5626596, 126.9226107, null, null, null, null, true, 'https://creatrip.com/en/spot/15429?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Korean']::text[], 'none', 'medium', false, true, false, false, true, 5, 45, 'korean'),
  ('15479', 'ECO JARDIN Myeongdong Branch', 'hair-salon', 'color-perm', 'Premium scalp and hair care using Shiseido, L''Oréal, and Milbon products, with an 18-step head spa option in central Myeongdong.', 'Myeongdong', 'Myeongdong, Jung-gu, Seoul', 37.5608977, 126.9863762, null, null, null, null, true, 'https://creatrip.com/en/spot/15479?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Korean']::text[], 'none', 'low', false, true, false, false, true, 4.9, 513, 'relaxing'),
  ('11138', 'Time On Me Studio', 'k-beauty', 'id-portrait', 'A Korean-style ID photo studio in Hongdae with professional photographers who handle both the shoot and the retouching, plus free rental of jackets and blouses.', 'Hongdae', null, 37.5503552, 126.9254349, 26, null, 30, null, true, 'https://creatrip.com/en/spot/11138?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Chinese']::text[], 'none', 'low', false, true, false, false, true, 4.9, 434, 'professional'),
  ('13315', 'Color of You Hongdae', 'k-beauty', 'color-analysis', 'English- and Chinese-interpreted personal color diagnosis near Hongdae Entrance Station, with product and color-application recommendations included.', 'Hongdae', null, 37.5503552, 126.9254349, 154, null, 60, null, true, 'https://creatrip.com/en/spot/13315?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Chinese', 'Japanese']::text[], 'none', 'low', false, true, false, false, true, 5, 397, 'korean'),
  ('13493', 'Pro Beauty', 'k-beauty', 'nail-art', 'A multi-seat nail studio three minutes from Myeongdong Station offering manicures, pedicures, eyelash styling, and waxing alongside a wide range of nail-art designs.', 'Myeongdong', null, 37.5612, 126.98802, 11, null, 60, null, true, 'https://creatrip.com/en/spot/13493?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Chinese']::text[], 'none', 'low', false, true, false, false, true, 4.6, 267, 'korean'),
  ('14157', 'NAIL BOX', 'k-beauty', 'nail-art', 'A clean, English-friendly nail studio six minutes from Hapjeong Station with a wide range of nail-art designs from cute to chic.', 'Hongdae', null, 37.5486897, 126.9142951, 22, null, 60, null, true, 'https://creatrip.com/en/spot/14157?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English']::text[], 'none', 'low', false, true, false, false, true, 5, 236, 'korean'),
  ('14844', 'AKNACK TOOL Cheongdam Branch', 'k-beauty', 'beauty-makeup', 'A Cheongdam-dong hair-and-makeup studio staffed by entertainment-industry stylists, combining haircuts and styling with a Jennymori scalp head-spa treatment in one visit.', 'Gangnam', null, 37.5257536, 127.0523217, null, null, 90, null, true, 'https://creatrip.com/en/spot/14844?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', '{}', 'none', 'low', false, true, false, false, true, 4.9, 77, 'professional'),
  ('14876', 'COCOREA', 'k-beauty', 'beauty-makeup', 'A Myeongdong hair-and-makeup studio built around artist Seo Su-jin''s 204-swatch personal color analysis, pairing the diagnosis with a full styling session.', 'Myeongdong', null, 37.5612, 126.98802, 34, null, 90, null, true, 'https://creatrip.com/en/spot/14876?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Korean']::text[], 'none', 'low', false, true, false, false, true, 4.9, 92, 'korean'),
  ('14955', 'Fleur Jardin Myeongdong Branch', 'k-beauty', 'aesthetics', 'A Myeongdong beauty lounge combining skincare, nail art, and a relaxing foot spa in one visit — a good breather stop in the middle of a shopping day.', 'Myeongdong', null, 37.5612, 126.98802, 29, null, 60, null, true, 'https://creatrip.com/en/spot/14955?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', '{}', 'none', 'low', false, true, false, false, true, 5, 638, 'relaxing'),
  ('15009', 'COLORIZE Myeongdong Main Branch', 'k-beauty', 'color-analysis', 'A pink, floral-themed personal-color studio steps from Myeongdong Station offering detailed color and body-type analysis plus a perfume-making and self-makeup add-on.', 'Myeongdong', null, 37.5612, 126.98802, 102, null, 90, null, true, 'https://creatrip.com/en/spot/15009?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Chinese', 'Japanese']::text[], 'none', 'low', false, true, false, false, true, 5, 201, 'korean'),
  ('15220', 'Sanho Mansion', 'k-beauty', 'id-portrait', 'An analog-inspired photo studio near Jongno 3-ga offering Korean-style ID photos and unscripted ''Random Gift'' shoots, bookable only through Creatrip.', null, null, 37.5714989, 126.9919062, 52, null, 40, null, true, 'https://creatrip.com/en/spot/15220?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', '{}', 'none', 'low', false, true, false, false, true, 4.9, 14, 'professional'),
  ('15245', 'Koho Nail', 'k-beauty', 'nail-art', 'A modern nail studio three minutes from COEX offering gel, art, and extension services for friends and family visiting together.', 'Gangnam', null, 37.5118733, 127.0591105, null, null, 60, null, true, 'https://creatrip.com/en/spot/15245?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English']::text[], 'none', 'low', false, true, false, false, true, 4.4, 18, 'korean'),
  ('15248', 'SlimM Main Branch', 'k-beauty', 'aesthetics', 'A K-pop-idol-favored contouring and lymphatic-therapy studio developed by ''JH Contouring'' creator Park Jung-hyun, spread across five private floors.', null, null, null, null, 57, null, 60, null, true, 'https://creatrip.com/en/spot/15248?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', '{}', 'none', 'medium', false, true, false, false, true, 4.9, 12, 'professional'),
  ('15473', 'CCLIME Seongsu Branch', 'k-beauty', 'aesthetics', 'A manual facial-contouring spa in Seongsu using hand techniques (no machines) plus a high-concentration lifting ampoule each session, popular with beauty insiders.', 'Seongsu', null, 37.5442441, 127.0634367, 149, null, 60, null, true, 'https://creatrip.com/en/spot/15473?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', '{}', 'none', 'medium', false, true, false, false, true, 5, 3, 'relaxing'),
  ('15480', 'CCLIME Gangnam HQ Branch', 'k-beauty', 'aesthetics', 'The Gangnam headquarters of CCLIME''s manual facial-contouring method, offering the same hand-technique sculpting and lifting-ampoule treatment as its other branches.', 'Gangnam', null, 37.5007251, 127.0263787, 149, null, 60, null, true, 'https://creatrip.com/en/spot/15480?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', '{}', 'none', 'medium', false, true, false, false, true, 4.7, 15, 'relaxing'),
  ('15729', 'Sola Spa', 'k-beauty', 'aesthetics', 'A private Myeongdong wellness spa three minutes from the station, moving from foot baths and Korean-style body scrubs to a scalp head-spa and facial skin care in one visit.', 'Myeongdong', null, 37.5612, 126.98802, 13, 29, 60, null, true, 'https://creatrip.com/en/spot/15729?utm_source=AFF-e2873zu&aff_id=AFF-e2873zu', ARRAY['English', 'Chinese', 'Japanese']::text[], 'none', 'low', false, true, false, false, true, 4.8, 257, 'relaxing')
on conflict (id) do update set
  name = excluded.name,
  parent_category = excluded.parent_category,
  subcategory = excluded.subcategory,
  description = excluded.description,
  area = excluded.area,
  address = excluded.address,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  price_min = excluded.price_min,
  price_max = excluded.price_max,
  duration_min = excluded.duration_min,
  opening_hours = excluded.opening_hours,
  booking_required = excluded.booking_required,
  booking_url = excluded.booking_url,
  languages = excluded.languages,
  downtime = excluded.downtime,
  procedure_intensity = excluded.procedure_intensity,
  needle_required = excluded.needle_required,
  tourist_friendly = excluded.tourist_friendly,
  factory_like = excluded.factory_like,
  upselling_risk = excluded.upselling_risk,
  price_transparency = excluded.price_transparency,
  rating = excluded.rating,
  review_count = excluded.review_count,
  experience_style = excluded.experience_style,
  updated_at = now();
