// Reads places.csv (creatrip_place_DB scraper output) and writes the same rows to:
//   - supabase/seed_places.sql     (Supabase `places` table, see supabase/places_schema.sql)
//   - src/data/glowUpPlaces.json   (bundled fallback / dev data, same row shape)
// Usage: node scripts/build-places.mjs [path/to/places.csv]
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const csvPath = path.resolve(process.argv[2] ?? path.join(root, 'places.csv'));

function parseCsv(text) {
  const rows = [];
  let row = [];
  let field = '';
  let quoted = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (quoted) {
      if (c !== '"') field += c;
      else if (text[i + 1] === '"') field += c, i++;
      else quoted = false;
    } else if (c === '"') quoted = true;
    else if (c === ',') row.push(field), (field = '');
    else if (c === '\n') row.push(field.replace(/\r$/, '')), rows.push(row), (row = []), (field = '');
    else field += c;
  }
  if (field || row.length) row.push(field), rows.push(row);
  return rows;
}

const list = (s) => (s ? s.split(';').map((x) => x.trim()).filter(Boolean) : []);
const num = (s) => (s === '' ? null : Number(s));
const int = (s) => (s === '' ? null : Number.parseInt(s, 10));

// "en:listed;ko:mentioned" -> [{ code, source }]
const languages = (s) => list(s).map((x) => {
  const [code, source] = x.split(':');
  return { code, source };
});

// "botox:low:0-1d;filler:high:1-7d" -> [{ key, downtime_grade, downtime_days_min, downtime_days_max }]
const procedures = (s) => list(s).flatMap((x) => {
  const [key, grade, days] = x.split(':');
  if (!key) return [];
  const m = /^(\d+)-(\d+)d$/.exec(days ?? '');
  return [{
    key,
    downtime_grade: grade || null,
    downtime_days_min: m ? Number(m[1]) : null,
    downtime_days_max: m ? Number(m[2]) : null,
  }];
});

const [header, ...body] = parseCsv(fs.readFileSync(csvPath, 'utf8').replace(/^﻿/, ''));
const rows = body
  .filter((r) => r.length === header.length)
  .map((r) => Object.fromEntries(header.map((h, i) => [h, r[i]])))
  .map((r) => ({
    id: r.id,
    name: r.name,
    subtype: r.subtype,
    extra_subtypes: list(r.extra_subtypes),
    onboarding: r.onboarding,
    city: r.city,
    region: r.region || null,
    lat: num(r.lat),
    lng: num(r.lng),
    address: r.address || null,
    nearest_station: r.nearest_station || null,
    price_type: r.price_type,
    price_min_usd: num(r.price_min_usd),
    deposit_usd: num(r.deposit_usd),
    languages: languages(r.languages),
    duration_min: int(r.duration_min),
    hours: r.hours || null,
    closed_days: list(r.closed_days),
    fix_targets: list(r.fix_targets),
    procedures: procedures(r.procedures),
    downtime_grade: r.downtime_grade || null,
    downtime_days_max: int(r.downtime_days_max),
    needs_before: list(r.needs_before),
    rating: num(r.rating),
    review_count: int(r.review_count),
    active: r.active.toLowerCase() === 'true',
    missing_fields: list(r.missing_fields),
    url: r.url,
    // Optional scraper columns (Creatrip "More than N global travelers have booked" + snapshot date).
    booked_count: int(r.booked_count ?? ''),
    captured_at: r.captured_at || null,
  }))
  .sort((a, b) => Number(a.id) - Number(b.id));

if (new Set(rows.map((r) => r.id)).size !== rows.length) throw new Error('duplicate place ids in CSV');
if (rows.length !== body.filter((r) => r.some(Boolean)).length) throw new Error('CSV has malformed rows');

const JSONB = new Set(['languages', 'procedures']);
const sql = (v, col) => {
  if (v == null) return 'null';
  if (JSONB.has(col)) return `${sql(JSON.stringify(v))}::jsonb`;
  if (typeof v === 'number' || typeof v === 'boolean') return String(v);
  if (Array.isArray(v)) return `array[${v.map((x) => sql(x)).join(', ')}]::text[]`;
  return `'${String(v).replace(/'/g, "''")}'`;
};

const cols = Object.keys(rows[0]);
const seed = [
  '-- Generated by scripts/build-places.mjs from places.csv - do not hand-edit.',
  '-- Run supabase/places_schema.sql first.',
  'begin;',
  'truncate public.places;',
  '',
  `insert into public.places (${cols.join(', ')}) values`,
  rows.map((r) => `(${cols.map((c) => sql(r[c], c)).join(', ')})`).join(',\n') + ';',
  '',
  'commit;',
  '',
].join('\n');

fs.writeFileSync(path.join(root, 'supabase', 'seed_places.sql'), seed);
fs.writeFileSync(path.join(root, 'src', 'data', 'glowUpPlaces.json'), JSON.stringify(rows, null, 2) + '\n');
console.log(`places: ${rows.length} (${rows.filter((r) => r.active).length} active) from ${path.relative(root, csvPath)}`);
